/* LANGUAGE */
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';

/* CONNECT TO CHATS */
export const CONNECT_TO_TWITCH_CHAT = 'CONNECT_TO_TWITCH_CHAT';
export const CONNECT_TO_AFREECA_CHAT = 'CONNECT_TO_AFREECA_CHAT';
export const CONNECT_TO_KAKAO_CHAT = 'CONNECT_TO_KAKAO_CHAT';
