/* LANGUAGE */
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';

/* CHANGE ID */
export const CHANGE_TWITCH_ID = 'CHANGE_TWITCH_ID';

/* CONNECT TO CHATS */
export const CONNECT_TO_TWITCH_CHAT = 'CONNECT_TO_TWITCH_CHAT';
export const CONNECT_TO_AFREECA_CHAT = 'CONNECT_TO_AFREECA_CHAT';
export const CONNECT_TO_KAKAO_CHAT = 'CONNECT_TO_KAKAO_CHAT';

/* Vote progress */
export const START_VOTE = 'START_VOTE';
export const END_VOTE = 'END_VOTE';
